# Generated by Django 4.0.2 on 2022-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0002_user_editor_alter_business_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='userimages/'),
        ),
    ]
