# Generated by Django 4.0.2 on 2022-06-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0002_alter_posts_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
