# Generated by Django 4.0.2 on 2022-06-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
