# Generated by Django 4.0.2 on 2022-06-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hapen', '0005_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='NeighbourHood_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hapen.neighbourhood'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('neighbourHood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hapen.neighbourhood')),
            ],
        ),
    ]
