# Generated by Django 4.0.2 on 2022-06-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0006_remove_posts_neighbourhood_id_posts_neighbourhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='editor',
        ),
    ]
