# Generated by Django 4.0.2 on 2022-06-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0007_remove_contacts_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='NeighbourHood_id',
            new_name='NeighbourHood',
        ),
    ]
