# Generated by Django 4.0.2 on 2022-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0008_rename_neighbourhood_id_user_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='businessimages/'),
        ),
    ]
