# Generated by Django 4.0.2 on 2022-06-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0010_neighbourhood_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='neighbourHood',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='NeighbourHood',
            new_name='Neighbourhood',
        ),
    ]
