# Generated by Django 4.0.2 on 2022-06-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0011_rename_neighbourhood_contacts_neighbourhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hapen.user'),
        ),
    ]
