# Generated by Django 4.0.2 on 2022-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0012_posts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
