# Generated by Django 4.0.2 on 2022-06-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0013_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
