# Generated by Django 4.0.2 on 2022-06-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0014_business_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Type',
            new_name='type',
        ),
    ]
