# Generated by Django 4.0.2 on 2022-06-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0015_rename_type_business_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user_name',
            new_name='Profile',
        ),
    ]
