# Generated by Django 4.0.2 on 2022-06-21 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hapen', '0016_rename_user_name_business_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='Profile',
        ),
        migrations.AddField(
            model_name='business',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
