# Generated by Django 4.0.2 on 2022-06-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapen', '0017_remove_business_profile_business_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
