# Generated by Django 4.0.2 on 2022-06-22 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hapen', '0018_alter_neighbourhood_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hapen.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture',
            field=models.ImageField(upload_to='businessimages/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='picture',
            field=models.ImageField(upload_to='hoodimages/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hapen.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hapen.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(upload_to='userimages/'),
        ),
    ]
